version: "2.2"

services:
  mongoDB:
    image: mongo
    container_name: mongoDB
    restart: always
    env_file:
      - .env
    ports:     
      - 27017:27017
    environment:     
      - MONGO_INITDB_DATABASE=${MONGO_DB_NAME}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
  aggregator:
    build:
      context: .
    command: npm run start
    volumes:
      - ".:/app/"
      - "/app/node_modules"
    env_file:
      - .env
    ports:
      - "3000:3000"
    environment:
      - DB_USERNAME=${MONGO_USER}
      - DB_PASSWORD=${MONGO_PASSWORD}
      - DB_NAME=${MONGO_DB_NAME}
      - DB_HOST=${MONGO_CONNECT_URL}
    links:
      - mongoDB
    depends_on:
      - mongoDB